### ISSUE TITLE
What do you think to add google analytics to the app ?

### ISSUE THREAD

**Issue by frlemieux** [d-k-ivanov/android-armenianalphabet#6]
- the users enabled western or eastern
- the users used the app in portrait or landscape
- track all the CTA

**Comment by frlemieux** [comment]
@d-k-ivanov Can you create a firebase app and google analytics project.
sha-1 of the app is required.
That I can integrate it...

**Comment by d-k-ivanov** [comment]
Hi Fred,
I don't mind to try analytics.
I've sent you firebase creds by email. And added you to google analytics project.

**Comment by d-k-ivanov** [comment]
And pushed firebase setting
