### ISSUE TITLE
Need to figure out how to add [u] sound.

### ISSUE THREAD

**Issue by d-k-ivanov** [d-k-ivanov/android-armenianalphabet#8]
I've got several review, that we've missed one letter which sounds like **`[u]`**.

I've figured out that there is digraph **`ու`**, which sounds like **`[u]`**, but consists from two letters: 
* **`ո`**, which sounds like **`[о]`**
* **`ւ`**,  which sounds like **`[w]`**

So those two sounds conjugated to [ow] (Something sounds like [ou])

I think it's better to add this digraph as independent unit.

**Comment by frlemieux** [comment]
I don t understand what is it exactly.

In classical orthography, ու and և are considered a digraph (ո + ւ) and a ligature (ե + ւ), respectively. In reformed orthography, they are separate letters of the alphabet.

source : https://en.wikipedia.org/wiki/Armenian_alphabet#ref_b

why add only this one ?

**Comment by d-k-ivanov** [comment]
I have reports from end users that we have missed one letter. And of course, we've used every wiki resource we can find, so we couldn't miss a letter. But those reports are about **`[u]`** sound, which people who know Armenian considering as separate letter with own sign. 

So I'm investigating if we can do something with it or no

**Comment by frlemieux** [comment]
From what I understood, it s not really a letter. I found explanation who said :
It like a word who means you and I.
I think the app is dedicated to beginner who need to listen and repeat the base letter.
I m not Armenian, but it doesn't look clear. I asked my friend who don t know exactly.
So, I think we need to have an advice from a specialist. Plus if people complain about it, it s very strange because if they know this specific thing. It doesn't mean they are beginner.

**Comment by d-k-ivanov** [comment]
I'm not Armenian, too, my wife is, so she is mine specialist, but she also couldn't give clear answers (but she went to primary school in Yerevan, so she knows the alphabet, and sure that there is no [u]-letter). Firstly I thought it's a difference between Eastern and Western, but it appeared that not, there is no such big difference in the alphabet.  

I think the problem occurs when you know how to speak Armenian, but know nothing about grammar, so one may think "I'm hearing [u]-letter, so it should be there", but there is no any [u]-letter. 

I agree, looks too unclear. I don't think we should implement such strange feature. Let's leave as is, and I'm going to answer on such comments, describing a bit of theory, which I managed to understand.

Thanks again for your participation! It's really great that we have two heads for such slimy questions.
